cache: bundler
before_install:
  - gem update bundler
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - rbx-2
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email:
    on_success: change
    on_failure: always
